version: '2'
services:
  acropolis-bdd:
    image: acropolis-bdd
    container_name: acropolis-bdd
    entrypoint:
      - docker/init_db.sh
    environment:
      - ACROPOLIS_HOSTNAME=localhost
    command: supervisord
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - postgres
      - fourstore
      - s3
    links:
      - postgres
      - fourstore
      - s3
    expose:
     - "80"
     - "8000"
    ports:
     - 80:80
     - 8000:8000

  # behave:
  #   container_name: behave
  #   command: behave
  #   #features/partitions.feature
  #   environment:
  #     - ACROPOLIS_HOSTNAME=acropolis.localhost
  #   build:
  #     context: .
  #     dockerfile: Dockerfile-behave
  #   depends_on:
  #     - acropolis-bdd
  #   links:
  #     - acropolis-bdd:acropolis.localhost


  # DB used to store the indexes
  postgres:
    image: postgres:9.1
    ports:
      - 5432:5432

  # Tstore for the output of twine-anansi and the command line client twine
  fourstore:
    image: cgueret/4store
    ports:
      - 9000:9000

  # S3 used to cache objects from Anansi and data processing output from Spindle
  s3:
    image: lphoward/fake-s3
    expose:
      - 80
    command: -r /fakes3_root -p 80
    ports:
      - 8080:80
