FROM debian:7.9
MAINTAINER Simeon van der Steen <simeon.vandersteen@bbc.co.uk>

ENV DEBIAN_FRONTEND noninteractive

RUN 	apt-get update && \
	apt-get install -y --no-install-recommends \
	ca-certificates git supervisor \
	build-essential automake gperf libtool flex bison \
	libssl-dev libraptor2-0 librasqal3 libraptor2-dev \
	librasqal3-dev ncurses-base libncurses5 \
	libncurses5-dev libreadline6-dev uuid-dev libglib2.0-dev

RUN	cd /usr/local/src && \
	git clone https://github.com/garlik/4store.git && \
	cd 4store && \
	./autogen.sh && \
	./configure && \
	make && \
	make install && \
	mkdir /var/log/4store

RUN 4s-backend-setup default

RUN echo '\
[supervisord]\n\
nodaemon=true\n\
\n\
[program:s4-backend]\n\
command=/usr/local/bin/4s-backend -D default\n\
\n\
[program:s4-httpd]\n\
command=/usr/local/bin/4s-httpd -D default \
' > /etc/supervisor/conf.d/4store.conf

EXPOSE 8080

CMD ["/usr/bin/supervisord"]
